name: Temporary rustfmt V43
on:
  pull_request:
    paths:
      - 'staging/**'
      - '.github/workflows/rustfmt-v43.yml'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: |
          echo BEGIN_FORMATTED_V43
          rustfmt --edition 2021 --emit stdout staging/multipage_buy.rs.txt | tail -n +3 | base64 -w0
          echo
          echo END_FORMATTED_V43
          rustfmt --edition 2021 --config skip_children=true --emit stdout staging/program_lib_v43.rs.txt | tail -n +3 | diff -u staging/program_lib_v43.rs.txt -
