name: Temporary Rustfmt V43 SBF
on:
  pull_request:
    paths:
      - 'staging/real_token_buy_v43.rs.txt'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: |
          echo BEGIN_FORMAT_SBF
          rustfmt --edition 2021 --emit stdout staging/real_token_buy_v43.rs.txt | tail -n +3 | base64 -w0
          echo
          echo END_FORMAT_SBF
